const ChapterArt = ({ kind }) => {
  const common = { width: "100%", height: "100%", viewBox: "0 0 800 500", preserveAspectRatio: "xMidYMid slice" };
  if (kind === "telescope") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("defs", null, /* @__PURE__ */ React.createElement("radialGradient", { id: "tg1", cx: "50%", cy: "50%", r: "50%" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: "#1a1d3a" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: "#05060f" }))), /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "url(#tg1)" }), Array.from({ length: 120 }).map((_, i) => {
    const x = i * 73 % 800, y = i * 131 % 500, r = i % 5 * 0.4 + 0.3;
    return /* @__PURE__ */ React.createElement("circle", { key: i, cx: x, cy: y, r, fill: "#fff", opacity: 0.3 + i % 7 * 0.1 }, /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: `${0.2};${0.9};${0.2}`, dur: `${2 + i % 4}s`, repeatCount: "indefinite", begin: `${i * 0.05}s` }));
  }), /* @__PURE__ */ React.createElement("g", { opacity: "0.8" }, [0, 1, 2, 3, 4].map((i) => /* @__PURE__ */ React.createElement("g", { key: i, transform: `translate(${500 + i * 30}, ${230 + i % 2 * 15})` }, /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "0", rx: "14", ry: "3", fill: "#e8c585" }), /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "0", rx: "14", ry: "3", fill: "none", stroke: "#f4d99f", strokeWidth: "0.5" }))), /* @__PURE__ */ React.createElement("g", { stroke: "#e8c585", strokeWidth: "0.5", opacity: "0.4", fill: "none" }, /* @__PURE__ */ React.createElement("line", { x1: "500", y1: "230", x2: "200", y2: "230" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "x2", values: "500;200;500", dur: "6s", repeatCount: "indefinite" })))), /* @__PURE__ */ React.createElement("g", { stroke: "#f4d99f", strokeWidth: "1", fill: "none", opacity: "0.5" }, /* @__PURE__ */ React.createElement("circle", { cx: "540", cy: "240", r: "80" }), /* @__PURE__ */ React.createElement("circle", { cx: "540", cy: "240", r: "120", strokeDasharray: "3 6" }), /* @__PURE__ */ React.createElement("line", { x1: "420", y1: "240", x2: "660", y2: "240", strokeDasharray: "2 8" }), /* @__PURE__ */ React.createElement("line", { x1: "540", y1: "120", x2: "540", y2: "360", strokeDasharray: "2 8" })));
  if (kind === "newspapers") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#0c0d18" }), [
    { x: 80, y: 120, r: -8 },
    { x: 280, y: 80, r: 5 },
    { x: 480, y: 140, r: -3 },
    { x: 120, y: 300, r: 7 },
    { x: 340, y: 280, r: -5 },
    { x: 550, y: 330, r: 3 },
    { x: 620, y: 90, r: 9 }
  ].map((p, i) => /* @__PURE__ */ React.createElement("g", { key: i, transform: `translate(${p.x},${p.y}) rotate(${p.r})`, opacity: "0.85" }, /* @__PURE__ */ React.createElement("rect", { width: "160", height: "200", fill: "#e8e3d6" }), /* @__PURE__ */ React.createElement("rect", { width: "160", height: "32", fill: "#1a1c2a" }), /* @__PURE__ */ React.createElement("text", { x: "80", y: "22", fontFamily: "serif", fontSize: "13", fontWeight: "700", fill: "#e8c585", textAnchor: "middle" }, "DOUBT"), [50, 70, 90, 110, 130, 150, 170].map((y) => /* @__PURE__ */ React.createElement("rect", { key: y, x: "14", y, width: 120 + y % 3 * 8, height: "3", fill: "#3a3530", opacity: "0.6" })))), /* @__PURE__ */ React.createElement("circle", { cx: "400", cy: "250", r: "200", fill: "#0c0d18", opacity: "0.55" }));
  if (kind === "wormhole") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("defs", null, /* @__PURE__ */ React.createElement("radialGradient", { id: "wh1", cx: "50%", cy: "50%", r: "50%" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: "#7c5cff" }), /* @__PURE__ */ React.createElement("stop", { offset: "40%", stopColor: "#241148" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: "#06030f" }))), /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#06030f" }), /* @__PURE__ */ React.createElement("g", { transform: "translate(400 250)" }, Array.from({ length: 12 }).map((_, i) => /* @__PURE__ */ React.createElement("ellipse", { key: i, cx: "0", cy: "0", rx: 300 - i * 22, ry: 140 - i * 10, fill: "none", stroke: "#a98bff", strokeWidth: "1", opacity: 0.15 + i * 0.05 }, /* @__PURE__ */ React.createElement("animateTransform", { attributeName: "transform", type: "rotate", from: i * 30, to: i * 30 + 360, dur: `${20 - i}s`, repeatCount: "indefinite" }))), /* @__PURE__ */ React.createElement("circle", { cx: "0", cy: "0", r: "80", fill: "url(#wh1)" }), /* @__PURE__ */ React.createElement("circle", { cx: "0", cy: "0", r: "40", fill: "#fff", opacity: "0.9" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "r", values: "40;55;40", dur: "3s", repeatCount: "indefinite" }))));
  if (kind === "reactor") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#1a0e08" }), /* @__PURE__ */ React.createElement("g", { transform: "translate(400 250)" }, /* @__PURE__ */ React.createElement("circle", { r: "180", fill: "none", stroke: "#3a1e0d", strokeWidth: "20" }), /* @__PURE__ */ React.createElement("circle", { r: "140", fill: "none", stroke: "#5a2b14", strokeWidth: "3", strokeDasharray: "4 8" }, /* @__PURE__ */ React.createElement("animateTransform", { attributeName: "transform", type: "rotate", from: "0", to: "360", dur: "14s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("circle", { r: "100", fill: "#ff8c3a", opacity: "0.6" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "r", values: "90;110;90", dur: "2s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("circle", { r: "60", fill: "#ffd07a" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: "1;0.6;1", dur: "0.8s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("circle", { r: "30", fill: "#fff" })));
  if (kind === "clock") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#0d0a06" }), /* @__PURE__ */ React.createElement("g", { transform: "translate(400 250)", stroke: "#e8c585", fill: "none" }, /* @__PURE__ */ React.createElement("circle", { r: "180", strokeWidth: "2", opacity: "0.6" }), /* @__PURE__ */ React.createElement("circle", { r: "160", strokeWidth: "0.5", strokeDasharray: "2 6" }), Array.from({ length: 60 }).map((_, i) => {
    const a = i * 6 * Math.PI / 180;
    const inner = i % 5 === 0 ? 160 : 170;
    return /* @__PURE__ */ React.createElement("line", { key: i, x1: Math.sin(a) * inner, y1: -Math.cos(a) * inner, x2: Math.sin(a) * 180, y2: -Math.cos(a) * 180, strokeWidth: i % 5 === 0 ? 2 : 1, opacity: "0.7" });
  }), /* @__PURE__ */ React.createElement("line", { x1: "0", y1: "0", x2: "0", y2: "-120", strokeWidth: "3", stroke: "#f4d99f" }, /* @__PURE__ */ React.createElement("animateTransform", { attributeName: "transform", type: "rotate", from: "0", to: "360", dur: "60s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("line", { x1: "0", y1: "0", x2: "0", y2: "-90", strokeWidth: "4", stroke: "#e8c585" }, /* @__PURE__ */ React.createElement("animateTransform", { attributeName: "transform", type: "rotate", from: "0", to: "360", dur: "720s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("circle", { r: "6", fill: "#f4d99f" })), /* @__PURE__ */ React.createElement("text", { x: "400", y: "450", textAnchor: "middle", fontFamily: "monospace", fontSize: "14", fill: "#e8c585", opacity: "0.6" }, "9,460,800,000 SECONDS"));
  if (kind === "abyss") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("defs", null, /* @__PURE__ */ React.createElement("linearGradient", { id: "ab1", x1: "0", y1: "0", x2: "0", y2: "1" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: "#0a3a52" }), /* @__PURE__ */ React.createElement("stop", { offset: "60%", stopColor: "#031824" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: "#000" }))), /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "url(#ab1)" }), Array.from({ length: 30 }).map((_, i) => {
    const x = i * 97 % 800, r = i % 4 + 2;
    return /* @__PURE__ */ React.createElement("circle", { key: i, cx: x, cy: "500", r, fill: "#5fb7d6", opacity: "0.4" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "cy", values: "500;-20", dur: `${6 + i % 5}s`, repeatCount: "indefinite", begin: `${i * 0.3}s` }));
  }), /* @__PURE__ */ React.createElement("g", { transform: "translate(400 240)" }, /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "0", rx: "60", ry: "22", fill: "#c8cad0" }), /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "0", rx: "60", ry: "22", fill: "none", stroke: "#5fb7d6", strokeWidth: "1" }), /* @__PURE__ */ React.createElement("circle", { cx: "20", cy: "-3", r: "6", fill: "#5fb7d6", opacity: "0.8" }), /* @__PURE__ */ React.createElement("line", { x1: "-90", y1: "0", x2: "-60", y2: "0", stroke: "#fff", strokeWidth: "3", opacity: "0.8" }), /* @__PURE__ */ React.createElement("path", { d: "M-95,-4 L-200,-30 L-200,30 L-95,4 Z", fill: "#5fb7d6", opacity: "0.15" })), /* @__PURE__ */ React.createElement("ellipse", { cx: "400", cy: "450", rx: "280", ry: "40", fill: "#000", opacity: "0.5" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "ry", values: "30;55;30", dur: "4s", repeatCount: "indefinite" })));
  if (kind === "cryopod") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#0a1218" }), [120, 260, 400, 540, 680].map((cx, i) => /* @__PURE__ */ React.createElement("g", { key: i, transform: `translate(${cx} 250)` }, /* @__PURE__ */ React.createElement("rect", { x: "-40", y: "-100", width: "80", height: "200", rx: "40", fill: "#1c2a36", stroke: "#5fb7d6", strokeWidth: "1" }), /* @__PURE__ */ React.createElement("rect", { x: "-30", y: "-90", width: "60", height: "180", rx: "30", fill: "#0f1e2a" }), /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "-30", rx: "20", ry: "28", fill: "#7adff0", opacity: "0.4" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: "0.2;0.6;0.2", dur: `${3 + i * 0.4}s`, repeatCount: "indefinite" })))), Array.from({ length: 50 }).map((_, i) => /* @__PURE__ */ React.createElement("circle", { key: i, cx: i * 61 % 800, cy: i * 89 % 500, r: "0.8", fill: "#bfe9f3", opacity: "0.3" })));
  if (kind === "pulse") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#06121a" }), /* @__PURE__ */ React.createElement("g", { transform: "translate(0 250)", stroke: "#5fb7d6", strokeWidth: "2", fill: "none" }, /* @__PURE__ */ React.createElement("path", { d: "M0,0 L100,0 L110,-30 L120,40 L130,-20 L140,0 L240,0 L250,-50 L260,60 L270,-30 L280,40 L290,0 L390,0 L400,-30 L410,40 L420,-20 L430,0 L530,0 L540,-50 L550,60 L560,-30 L570,40 L580,0 L800,0" })), /* @__PURE__ */ React.createElement("text", { x: "400", y: "100", textAnchor: "middle", fontFamily: "monospace", fontSize: "14", fill: "#5fb7d6", opacity: "0.7" }, "TRENCH SENSOR \xB7 3\xB75\xB73\xB75"));
  if (kind === "valen") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("defs", null, /* @__PURE__ */ React.createElement("radialGradient", { id: "vg", cx: "50%", cy: "50%" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: "#1a1224" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: "#06040c" }))), /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "url(#vg)" }), /* @__PURE__ */ React.createElement("g", null, /* @__PURE__ */ React.createElement("circle", { cx: "180", cy: "250", r: "14", fill: "#f4d99f" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "r", values: "12;18;12", dur: "3s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("circle", { cx: "620", cy: "250", r: "14", fill: "#a98bff" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "r", values: "12;18;12", dur: "3s", repeatCount: "indefinite", begin: "1.5s" })), /* @__PURE__ */ React.createElement("line", { x1: "180", y1: "250", x2: "620", y2: "250", stroke: "#7c5cff", strokeWidth: "1", strokeDasharray: "4 8", opacity: "0.6" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "stroke-dashoffset", from: "0", to: "-24", dur: "2s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("text", { x: "180", y: "290", fontFamily: "serif", fontSize: "14", fill: "#f4d99f", textAnchor: "middle", opacity: "0.8" }, "CAMILA"), /* @__PURE__ */ React.createElement("text", { x: "620", y: "290", fontFamily: "serif", fontSize: "14", fill: "#a98bff", textAnchor: "middle", opacity: "0.8" }, "VALEN")));
  if (kind === "mosaic") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#1a1612" }), Array.from({ length: 80 }).map((_, i) => {
    const x = i * 47 % 800, y = i * 73 % 500, s = 30 + i % 4 * 15;
    const colors = ["#3a4d3c", "#5a3a2c", "#3c4d5a", "#5a4a2c", "#3a2c4d"];
    return /* @__PURE__ */ React.createElement("rect", { key: i, x, y, width: s, height: s, fill: colors[i % 5], opacity: "0.7" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: "0.4;0.9;0.4", dur: `${4 + i % 6}s`, repeatCount: "indefinite", begin: `${i * 0.1}s` }));
  }), /* @__PURE__ */ React.createElement("rect", { x: "0", y: "0", width: "800", height: "500", fill: "#0a0a0a", opacity: "0.3" }));
  if (kind === "flame") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#0d0606" }), /* @__PURE__ */ React.createElement("g", { transform: "translate(400 280)" }, Array.from({ length: 8 }).map((_, i) => /* @__PURE__ */ React.createElement("ellipse", { key: i, cx: "0", cy: -i * 20, rx: 80 - i * 8, ry: 100 - i * 10, fill: i % 2 ? "#ff6a2a" : "#ffaa3a", opacity: 0.5 - i * 0.05 }, /* @__PURE__ */ React.createElement("animate", { attributeName: "ry", values: `${100 - i * 10};${110 - i * 10};${100 - i * 10}`, dur: `${1 + i * 0.2}s`, repeatCount: "indefinite" })))), Array.from({ length: 40 }).map((_, i) => /* @__PURE__ */ React.createElement("circle", { key: i, cx: 350 + i * 37 % 100, cy: 300 - i * 53 % 200, r: "1", fill: "#ffd07a" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "cy", values: "300;100", dur: `${2 + i % 3}s`, repeatCount: "indefinite", begin: `${i * 0.15}s` }), /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: "1;0", dur: `${2 + i % 3}s`, repeatCount: "indefinite", begin: `${i * 0.15}s` }))));
  if (kind === "fleet") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#080a18" }), Array.from({ length: 80 }).map((_, i) => {
    const x = i * 73 % 800, y = i * 101 % 500;
    return /* @__PURE__ */ React.createElement("circle", { key: i, cx: x, cy: y, r: "0.5", fill: "#fff", opacity: "0.6" });
  }), [
    { x: 100, y: 200, s: 1.4 },
    { x: 200, y: 240, s: 1 },
    { x: 280, y: 180, s: 0.8 },
    { x: 360, y: 260, s: 1.2 },
    { x: 440, y: 200, s: 0.9 },
    { x: 520, y: 240, s: 1.1 },
    { x: 600, y: 180, s: 1 },
    { x: 680, y: 260, s: 1.3 }
  ].map((p, i) => /* @__PURE__ */ React.createElement("g", { key: i, transform: `translate(${p.x} ${p.y}) scale(${p.s})` }, /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "0", rx: "22", ry: "5", fill: "#a98bff" }), /* @__PURE__ */ React.createElement("ellipse", { cx: "0", cy: "0", rx: "22", ry: "5", fill: "none", stroke: "#dcd0ff", strokeWidth: "0.5" }), /* @__PURE__ */ React.createElement("circle", { cx: "-15", cy: "0", r: "2", fill: "#fff", opacity: "0.8" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: "0.4;1;0.4", dur: "2s", repeatCount: "indefinite", begin: `${i * 0.3}s` })))));
  if (kind === "letters") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#1a1408" }), Array.from({ length: 14 }).map((_, i) => {
    const x = 60 + i * 55 % 680, y = 60 + Math.floor(i / 12) * 180 + i % 3 * 30, r = i % 5 * 4 - 8;
    return /* @__PURE__ */ React.createElement("g", { key: i, transform: `translate(${x} ${y}) rotate(${r})` }, /* @__PURE__ */ React.createElement("rect", { width: "120", height: "80", fill: "#f4ead2", opacity: "0.9" }), [15, 30, 45, 60].map((yy) => /* @__PURE__ */ React.createElement("rect", { key: yy, x: "10", y: yy, width: 90 - yy % 20, height: "2", fill: "#3a3020", opacity: "0.5" })));
  }));
  if (kind === "alarm") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#1a0808" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "fill", values: "#1a0808;#3a0a0a;#1a0808", dur: "1.4s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("g", { transform: "translate(400 250)" }, /* @__PURE__ */ React.createElement("circle", { r: "120", fill: "#ff3030", opacity: "0.3" }, /* @__PURE__ */ React.createElement("animate", { attributeName: "r", values: "80;180;80", dur: "1.4s", repeatCount: "indefinite" }), /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: "0.5;0;0.5", dur: "1.4s", repeatCount: "indefinite" })), /* @__PURE__ */ React.createElement("circle", { r: "60", fill: "#ff5050" }), /* @__PURE__ */ React.createElement("text", { y: "8", textAnchor: "middle", fontFamily: "monospace", fontSize: "22", fontWeight: "700", fill: "#fff" }, "!")));
  if (kind === "mars") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("defs", null, /* @__PURE__ */ React.createElement("radialGradient", { id: "mr", cx: "40%", cy: "40%" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: "#ff9866" }), /* @__PURE__ */ React.createElement("stop", { offset: "60%", stopColor: "#a04020" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: "#3a1408" }))), /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#1a0a08" }), /* @__PURE__ */ React.createElement("circle", { cx: "500", cy: "240", r: "180", fill: "url(#mr)" }), /* @__PURE__ */ React.createElement("ellipse", { cx: "460", cy: "200", rx: "40", ry: "15", fill: "#7a2810", opacity: "0.5" }), /* @__PURE__ */ React.createElement("ellipse", { cx: "540", cy: "280", rx: "35", ry: "12", fill: "#7a2810", opacity: "0.5" }), /* @__PURE__ */ React.createElement("circle", { cx: "500", cy: "240", r: "180", fill: "none", stroke: "#ffaa66", strokeWidth: "0.5", opacity: "0.4" }), Array.from({ length: 60 }).map((_, i) => /* @__PURE__ */ React.createElement("circle", { key: i, cx: i * 67 % 800, cy: i * 43 % 500, r: "0.7", fill: "#fff", opacity: "0.5" })));
  if (kind === "voice") return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("defs", null, /* @__PURE__ */ React.createElement("radialGradient", { id: "vc", cx: "50%", cy: "50%" }, /* @__PURE__ */ React.createElement("stop", { offset: "0%", stopColor: "#1a3a52" }), /* @__PURE__ */ React.createElement("stop", { offset: "100%", stopColor: "#000" }))), /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "url(#vc)" }), [40, 80, 120, 160, 200, 240].map((r, i) => /* @__PURE__ */ React.createElement("circle", { key: i, cx: "400", cy: "250", r, fill: "none", stroke: "#5fb7d6", strokeWidth: "1", opacity: 0.6 - i * 0.08 }, /* @__PURE__ */ React.createElement("animate", { attributeName: "r", values: `${r - 20};${r + 40};${r - 20}`, dur: `${3 + i * 0.3}s`, repeatCount: "indefinite" }), /* @__PURE__ */ React.createElement("animate", { attributeName: "opacity", values: `${0.6 - i * 0.08};0;${0.6 - i * 0.08}`, dur: `${3 + i * 0.3}s`, repeatCount: "indefinite" }))), /* @__PURE__ */ React.createElement("text", { x: "400", y: "250", textAnchor: "middle", fontFamily: "serif", fontSize: "22", fill: "#5fb7d6", opacity: "0.9", letterSpacing: "3" }, "WE ARE STILL HERE"));
  return /* @__PURE__ */ React.createElement("svg", { ...common }, /* @__PURE__ */ React.createElement("rect", { width: "800", height: "500", fill: "#111" }));
};
window.ChapterArt = ChapterArt;
