// Glossary: term -> { def, mnemonic, phon }
window.GLOSSARY = {
  "depths": { phon:"DEPTHS", def: "The deepest, darkest, most faraway parts of something — like deep space or the deep ocean.", mnemonic: "Depth = how DEEP. Picture a diver dropping down, down, down." },
  "massive": { phon:"MASS-iv", def: "Huge. Much, much bigger than normal.", mnemonic: "MASS-ive things have lots of mass — like a planet, or a whale." },
  "cosmos": { phon:"KOZ-mohs", def: "Another word for the whole universe — all of space and everything in it.", mnemonic: "Cosmos sounds like COSMETICS for the universe — stars, planets, and dust everywhere." },
  "half the speed of light": { phon:"haf · the · speed · of · lite", def: "Light travels 186,000 miles every second. Half of that speed is still so fast it could circle Earth about three and a half times in one second.", mnemonic: "Half-light = still ridiculously fast. Three Earth laps in one blink." },
  "engineer": { phon:"en-juh-NEER", def: "A person who designs and builds machines, buildings, bridges, or other useful things.", mnemonic: "An ENGINE-eer fixes the engine — and everything else that's built." },
  "propulsion": { phon:"pruh-PUHL-shun", def: "The thing that pushes a ship, rocket, or car forward. A rocket's fire is its propulsion.", mnemonic: "PRO-PULSE-ion = the PUSH that PROpels you forward." },
  "natural phenomenon": { phon:"NAT-chur-uhl · fuh-NOM-uh-non", def: "Something that happens in nature on its own, like lightning, rainbows, or volcanoes. Not made by people.", mnemonic: "Natural = nature did it. Phenomenon = a wow-thing." },
  "biologist": { phon:"by-OL-uh-jist", def: "A scientist who studies living things — plants, animals, people, germs, and anything alive.", mnemonic: "BIO = life. A biologist studies life." },
  "organic": { phon:"or-GAN-ik", def: "Made of living things, or once alive. Your body is organic. A rock is not.", mnemonic: "Organic = comes from an ORGAN-ism. Living, or once-living." },
  "strategist": { phon:"STRAT-uh-jist", def: "Someone who is good at making plans, especially tricky ones with lots of steps.", mnemonic: "Strategist plans STRATEGIES — the secret moves to win the game." },
  "frequencies": { phon:"FREE-kwen-seez", def: "Different kinds of radio or sound waves. Each station on a radio has its own frequency.", mnemonic: "Tune the radio dial = surf the FREQUENCIES." },
  "artificial": { phon:"ar-tuh-FISH-uhl", def: "Made by a machine or a person, not by nature. An artificial voice is a computer voice.", mnemonic: "ARTificial = made by ART (human craft), not by nature." },
  "invaders": { phon:"in-VAY-derz", def: "People (or aliens) who come to take over a place by force.", mnemonic: "Invaders INVADE — they barge in uninvited." },
  "tiny wormhole": { phon:"TY-nee · WURM-hohl", def: "A shortcut through space. Imagine folding a piece of paper so two far-apart dots touch — that's a wormhole. A tiny one can pass signals, not spaceships.", mnemonic: "Fold the paper so two dots kiss — a wormhole. The tiny one only fits whispers." },
  "wormhole": { phon:"WURM-hohl", def: "A shortcut through space. Imagine folding a piece of paper so two far-apart dots touch — that's a wormhole.", mnemonic: "Fold the paper so two dots kiss." },
  "exchanged nervous glances": { phon:"eks-CHAYNJD · NUR-vus · GLAN-sez", def: "Looked at each other quickly, worried about what was happening.", mnemonic: "Eyes flick to friend, friend flicks back: 'uh oh.'" },
  "allies": { phon:"AL-eyez", def: "Friends or partners who help each other, especially in a big fight or challenge.", mnemonic: "Allies = AllIES on your side." },
  "governments": { phon:"GUV-urn-ments", def: "The groups of people who run a country and make its rules.", mnemonic: "Government GOVERNS — sets the rules." },
  "emergency": { phon:"ih-MUR-jen-see", def: "Something serious that happens suddenly and needs fast action.", mnemonic: "EMERGEncy = something EMERGES fast — alarms blaring." },
  "debated": { phon:"dih-BAY-ted", def: "Argued or talked through different sides of a question.", mnemonic: "A debate is a verbal tug-of-war: I'm right! No, I am!" },
  "advanced": { phon:"ad-VANSST", def: "Far ahead — smarter, stronger, or more developed than most.", mnemonic: "Advanced = ahead. Already won the race the rest hasn't started." },
  "civilization": { phon:"siv-uh-luh-ZAY-shun", def: "A large group of people who live together and share a way of life, cities, and rules.", mnemonic: "CIVILization = where CIVILIANS live together." },
  "protests": { phon:"PROH-tests", def: "Groups of people gathering to show they don't agree with something.", mnemonic: "Pro-TEST = TESTING the rules out loud, in public." },
  "erupted": { phon:"ih-RUP-ted", def: "Burst out suddenly, like a volcano or a big reaction.", mnemonic: "Erupt like a volcano — POW, instantly." },
  "weapons": { phon:"WEP-unz", def: "Tools made for fighting — guns, swords, missiles, or anything used in battle.", mnemonic: "Weapons = the WEAR-and-tear tools of war." },
  "peace offerings": { phon:"PEESS · OFF-er-ings", def: "Gifts or messages that show you want to be friendly, not fight.", mnemonic: "A gift wrapped in a white flag." },
  "digital": { phon:"DIJ-uh-tuhl", def: "Made of numbers and code, the way computers store information.", mnemonic: "DIGITs = numbers. Digital = made of digits." },
  "mathematical": { phon:"math-uh-MAT-ih-kuhl", def: "Made of numbers, math, and logic.", mnemonic: "Math + magical = MATHEMATICAL." },
  "universal patterns": { phon:"yoo-nih-VUR-suhl · PAT-urnz", def: "Ideas or rules that would be true anywhere in the universe — like 2 + 2 = 4 no matter what planet you're on.", mnemonic: "2+2=4 on Earth, on Mars, in the next galaxy. UNIVERSAL." },
  "shiver": { phon:"SHIV-er", def: "A quick shake of your body, usually when you're cold or scared.", mnemonic: "Brrrr — a shiver-shake down your spine." },
  "complex mathematical sequences": { phon:"KOM-pleks · math-uh-MAT-ih-kuhl · SEE-kwen-sez", def: "Long, tricky lists of numbers that follow a rule. Like codes made of math.", mnemonic: "Codes built from numbers: 1, 1, 2, 3, 5, 8…" },
  "deliberate": { phon:"dih-LIB-er-it", def: "Careful and on purpose. Not by accident.", mnemonic: "DE-LIBERATE = LIBERATED from accident — done on purpose." },
  "9,460,800,000 seconds": { phon:"nine · BIL-yun · four-HUN-dred-six-tee · MIL-yun · SEK-undz", def: "That's how many seconds are in three hundred years. It's a huge number, but seconds add up fast.", mnemonic: "Nine BILLION ticks of a clock = 300 years." },
  "common ground": { phon:"KOM-un · grownd", def: "Something two different groups agree on or share — a starting place to work together.", mnemonic: "Two people standing on the same patch of dirt." },
  "fusion energy": { phon:"FYOO-zhun · EN-er-jee", def: "The same kind of power that makes the sun shine. You squeeze tiny bits of hydrogen together so hard they stick and release a burst of energy.", mnemonic: "FUSE two atoms into one. Sun-power in a bottle." },
  "Mariana Trench": { phon:"mair-ee-AH-nuh · trench", def: "The deepest place in any ocean on Earth. It's almost seven miles deep — deeper than Mount Everest is tall.", mnemonic: "Mt. Everest, upside down, in the ocean — and still not at the bottom." },
  "density reading": { phon:"DEN-suh-tee · REE-ding", def: "A measurement of how heavy something is for its size. A small brick is dense. A big marshmallow is not.", mnemonic: "Brick: heavy for its size. Marshmallow: light. Density!" },
  "excited": { phon:"ek-SY-ted", def: "Full of energy and eager — not afraid, but ready to go.", mnemonic: "Excited = ex-SEAT-ed — can't sit still!" },
  "Indestructium": { phon:"in-dee-STRUK-tee-um", def: "A made-up name for a made-up metal in this book. It means 'the metal that cannot be destroyed.'", mnemonic: "IN- (not) + DESTRUCT (break) + -IUM (a metal). Unbreakable metal." },
  "Dyson Sphere": { phon:"DY-sun · sfeer", def: "A giant ball or ring built all the way around a star to catch its energy. No one has ever built one. Some scientists think a very advanced civilization could.", mnemonic: "Wrap a star in a giant ball to drink its sunlight." },
  "one-mile-long": { phon:"wun · myle · lawng", def: "A mile is 5,280 feet. A one-mile-long drill is about as long as eighteen football fields lined up end to end.", mnemonic: "18 football fields, end to end. That's the drill." },
  "energy source": { phon:"EN-er-jee · sorss", def: "A place that gives off power. The sun is an energy source. A battery is too.", mnemonic: "A power plug into the world." },
  "fusion power": { phon:"FYOO-zhun · POW-er", def: "Same idea as fusion energy — power made by squeezing tiny atoms together, like the sun does.", mnemonic: "Sun in a box." },
  "patterns": { phon:"PAT-urnz", def: "Things that repeat in the same way. A heartbeat is a pattern. Stripes on a zebra are a pattern.", mnemonic: "Boom-boom, boom-boom — a heartbeat is a pattern." },
  "Chaos Plan": { phon:"KAY-oss · plan", def: "Sophia's plan to beat the Fortitude by making everything messy and confusing, so their orders stop working.", mnemonic: "Make it messy on purpose — that's the Chaos Plan." },
  "electromagnetic disruptors": { phon:"ih-LEK-troh-mag-NET-ik · diss-RUP-terz", def: "Machines that fill the air with invisible static. They stop radios, phones, and alien ships from talking to each other.", mnemonic: "Invisible static blanket — no signals get through." },
  "fake": { phon:"fayk", def: "Not real. Made to trick someone.", mnemonic: "Fake = a fake-out." },
  "the Fortitude Accord": { phon:"thuh · FOR-tih-tood · uh-KORD", def: "The big agreement where every country on Earth promised to work as one team against the Fortitude.", mnemonic: "Accord = AGREEMENT. Earth's biggest pinky-promise." },
  "Accord": { phon:"uh-KORD", def: "An agreement — a promise between groups to work together.", mnemonic: "Accord = AGREEMENT, set to music." },
  "ISV Pioneer": { phon:"eye · ess · vee · PY-uh-neer", def: "The name of Earth's first full-size Indestructium spaceship. ISV stands for 'Indestructium Space Vessel.'", mnemonic: "I.S.V. = Indestructium Space Vessel. The first one is the Pioneer." },
  "greenhouse gases": { phon:"GREEN-howss · GAS-ez", def: "Gases like carbon dioxide that trap heat and warm up a planet's air. Too much on Earth causes problems. Just the right amount on Mars could help it become livable.", mnemonic: "Wrap the planet in a glass blanket — heat stays in." },
  "gravity folding": { phon:"GRAV-ih-tee · FOHL-ding", def: "The Fortitude's way of bending space to travel fast — like folding a map so two cities touch, then stepping across the fold.", mnemonic: "Fold the map. Step across. You're there." },
  "exoskeleton": { phon:"EK-soh-SKEL-uh-tun", def: "A hard outside shell that protects a body. Crabs, lobsters, and beetles have exoskeletons. So do the Fortitude.", mnemonic: "EXO = OUTSIDE. Skeleton on the OUTSIDE — like a crab." },
  // Added for fuller coverage in every chapter
  "astronomer": { phon:"uh-STRON-uh-mer", def: "A scientist who studies stars, planets, and space.", mnemonic: "ASTRO = stars. An astronomer watches the stars." },
  "headlines": { phon:"HED-lynez", def: "The big bold words at the top of a news story.", mnemonic: "The HEAD of the article — the LINE you read first." },
  "reporter": { phon:"rih-POR-ter", def: "Someone whose job is to find news and tell other people about it.", mnemonic: "A reporter REPORTS what just happened." },
  "editorial": { phon:"ed-uh-TOR-ee-uhl", def: "An opinion piece in a newspaper. The writer says what they think, not just what happened.", mnemonic: "An EDITOR writes their opinion — that's an editorial." },
  "reactor": { phon:"ree-AK-ter", def: "A big machine that makes power from a controlled reaction — like fusion.", mnemonic: "RE-ACTOR = where the reaction acts." },
  "fusion": { phon:"FYOO-zhun", def: "Squeezing tiny atoms together so hard they stick and release a burst of energy. The sun does this all day.", mnemonic: "FUSE two into one — sun-power in a bottle." },
  "coolant": { phon:"KOO-lunt", def: "A liquid or gas that keeps something from getting too hot — like the water that cools a car engine.", mnemonic: "Coolant keeps it COOL." },
  "plasma": { phon:"PLAZ-muh", def: "Gas that has been heated so hot it glows. The sun is made of plasma.", mnemonic: "Plasma = gas turned into glowing soup." },
  "cryosleep": { phon:"KRY-oh-sleep", def: "A way of freezing your body so you can sleep for years without aging much. CRYO means very cold.", mnemonic: "CRYO = cold. Sleep on ice." },
  "cryopod": { phon:"KRY-oh-pod", def: "The freezing-cold capsule a person sleeps inside during cryosleep.", mnemonic: "A cold pod — like a pea in an icy pod." },
  "malfunction": { phon:"mal-FUNK-shun", def: "When a machine breaks or stops working the way it should. MAL means bad.", mnemonic: "MAL (bad) + FUNCTION (working) = NOT working." },
  "translator": { phon:"trans-LAY-ter", def: "Someone who turns words from one language into another.", mnemonic: "Translates one tongue into another." },
  "decode": { phon:"dee-KOHD", def: "To figure out a secret or hidden message.", mnemonic: "DE- (undo) + CODE = unlock the code." },
  "saboteur": { phon:"sab-uh-TUR", def: "Someone who sneaks in and breaks something on purpose.", mnemonic: "A SABOTEUR SABotages — wrecks things in secret." },
  "lithium": { phon:"LITH-ee-um", def: "A light, silvery metal used inside almost every battery — phones, electric cars, spaceships.", mnemonic: "Inside every battery: lithium." },
  "diplomat": { phon:"DIP-luh-mat", def: "A person whose job is to talk between countries and try to keep peace.", mnemonic: "A diplomat does DIPLOMACY — careful talking instead of fighting." },
  "disruptor": { phon:"diss-RUP-ter", def: "A machine that interrupts signals — making radios, phones, or alien orders stop working.", mnemonic: "Disrupts = breaks up — like a kid yelling during quiet time." },
  "terraform": { phon:"TAIR-uh-form", def: "To turn a lifeless planet (like Mars) into a place where people can live, by changing its air, water, and soil.", mnemonic: "TERRA = earth. To EARTH-shape a planet." },
  "orbit": { phon:"OR-bit", def: "The curved path one object takes around another — like the moon around Earth.", mnemonic: "Round and round — that's an orbit." },
  "lab": { phon:"LAB", def: "Short for LABORATORY — a room where scientists do experiments.", mnemonic: "Lab = where science happens." },
  "data": { phon:"DAY-tuh", def: "Information — usually numbers, measurements, or facts a computer can use.", mnemonic: "Data = the numbers and notes science is built on." },
  "sensor": { phon:"SEN-ser", def: "A tool that senses something — heat, light, sound, motion — and turns it into data.", mnemonic: "A sensor SENSES things you can't see." },
  "fleet": { phon:"FLEET", def: "A big group of ships traveling together.", mnemonic: "A fleet of ships sails as one." },
  "century": { phon:"SEN-chuh-ree", def: "One hundred years.", mnemonic: "A CENTury = 100 years (like a CENT is 1/100 of a dollar)." },
  "centuries": { phon:"SEN-chuh-reez", def: "Hundreds of years. Three centuries = three hundred years.", mnemonic: "Many CENTuries stacked up — many hundreds of years." },
  "physicist": { phon:"FIZ-uh-sist", def: "A scientist who studies how the universe works — energy, matter, gravity, light.", mnemonic: "PHYSICS scientist = physicist." },
  "submarine": { phon:"SUB-muh-reen", def: "A ship that travels under the water.", mnemonic: "SUB (under) + MARINE (sea) = under the sea." },
  "drill": { phon:"DRILL", def: "A spinning tool that bores holes into hard things.", mnemonic: "Drrrr-rill — spin and bore." },
  "trench": { phon:"TRENCH", def: "A long, narrow ditch — on the ocean floor, the deepest cracks in the Earth.", mnemonic: "A trench is a long, deep dig." },
  "telescope": { phon:"TEL-uh-skohp", def: "A tube with lenses inside that lets you see things far away — like stars and planets.", mnemonic: "TELE (far) + SCOPE (see) = see far." },
  "alien": { phon:"AY-lee-un", def: "A living thing from another planet.", mnemonic: "Alien = NOT from here." },
  "captain": { phon:"KAP-tin", def: "The person in charge of a ship or a team.", mnemonic: "The captain calls the shots." },
  "sonar": { phon:"SOH-nar", def: "A way of using sound to 'see' underwater. The sound bounces back and shows what's there.", mnemonic: "Ping… ping… listen for the bounce." },
  "shipyard": { phon:"SHIP-yard", def: "A place where ships are built.", mnemonic: "A YARD where SHIPS grow." }
};

window.CHAPTERS_META = [
  { num:1, title:"A Strange Discovery", subtitle:"Camila sees something impossible", art:"telescope", palette:"night" },
  { num:2, title:"The Doubters", subtitle:"The whole world says she's wrong", art:"newspapers", palette:"dim" },
  { num:3, title:"The Fortitude's Message", subtitle:"A robotic voice in the dark", art:"wormhole", palette:"violet" },
  { num:4, title:"The First Failure", subtitle:"A reactor, a burn, a hard lesson", art:"reactor", palette:"ember" },
  { num:5, title:"Racing Against Time", subtitle:"Three hundred years. Nine billion seconds.", art:"clock", palette:"amber" },
  { num:6, title:"The Deep-Sea Mission", subtitle:"Seven miles down — and something looks back", art:"abyss", palette:"deep" },
  { num:7, title:"The Long Sleep", subtitle:"Cryosleep, and goodbye to the world they knew", art:"cryopod", palette:"ice" },
  { num:8, title:"Secrets of the Stars", subtitle:"Fusion holds. The trench taps back.", art:"pulse", palette:"violet" },
  { num:9, title:"A Voice in the Dark", subtitle:"A name on the other side of the wormhole", art:"valen", palette:"warm" },
  { num:10, title:"The Fortitude's Weakness", subtitle:"They don't know how to argue", art:"mosaic", palette:"earth" },
  { num:11, title:"The Holdout and the Saboteur", subtitle:"One country says no. A reactor blows.", art:"flame", palette:"ember" },
  { num:12, title:"The Battle Plan", subtitle:"We will discuss.", art:"fleet", palette:"violet" },
  { num:13, title:"Through Valen's Eyes", subtitle:"Why do you help us?", art:"letters", palette:"warm" },
  { num:14, title:"The Final Wake-Up", subtitle:"Five teammates. Not six.", art:"alarm", palette:"dim" },
  { num:15, title:"The Choice", subtitle:"A bare hand on red dust", art:"mars", palette:"mars" },
  { num:16, title:"What Waits Below", subtitle:"We are still here.", art:"voice", palette:"deep" }
];

window.QUIZ = {
  1: [
    { q: "What does Camila see on her telescope screen at the start of the chapter?", type:"mc", choices:["A new comet streaking past Mars","A fleet of huge alien ships moving toward Earth","A hidden moon orbiting Saturn","A bright nova she's never seen before"], correct:1, explain:"It was a fleet of enormous ships moving together through the cosmos — heading toward Earth." },
    { q: "Match each teammate to her job — who is the engineer?", type:"mc", choices:["Zoe","Kennedy","Ava","Patriya"], correct:1, explain:"Kennedy is the engineer. Zoe = physicist, Ava = biologist, Patriya = deep-sea expert, Annabelle = strategist." },
    { q: "How long does the team have until the Fortitude arrive?", type:"mc", choices:["30 years","100 years","300 years","3,000 years"], correct:2, explain:"The ships are 20 light-years away, traveling at half the speed of light. That works out to three hundred years." },
    { q: "What does the Fortitude's first message say?", type:"mc", choices:["They come in peace and bring gifts","Their star is dying and they need a new home","Earth has been claimed for the Empire","They are merely passing through"], correct:1, explain:"'We are the Fortitude. Our home star is dying. We must find a new planet. We will arrive in three centuries.'" },
    { q: "Why does Camila feel afraid at the very end of the chapter?", type:"open", hint:"Think about what 'a new home' might mean for Earth.", model:"Because she realizes Earth might be the new home the Fortitude are coming to take." }
  ],
  2: [
    { q: "Who is Dr. Marcus Webb, and what does he say about Camila's discovery?", type:"mc", choices:["A young rival astronomer who agrees with her","A famous astronomer who calls her data a sensor glitch","A reporter who praises her work","A government official who funds the lab"], correct:1, explain:"He's a famous, respected astronomer who says her 'fleet' is just a sensor glitch and her data is wrong." },
    { q: "Why does Camila almost delete her data?", type:"mc", choices:["A computer virus told her to","Because the whole world starts to believe Webb and she begins to doubt herself","Because Zoe asked her to","To make room on her hard drive"], correct:1, explain:"She begins to doubt herself when the world turns against her. Quitting would make the fight go away." },
    { q: "What does Kennedy do when she finds Camila alone in the lab?", type:"mc", choices:["Tells her to give up","Brings her coffee and starts checking the numbers a third time","Calls a reporter","Yells at Dr. Webb on TV"], correct:1, explain:"She quietly brings coffee and starts checking the numbers a third time, without being asked." },
    { q: "What does Ava's grandmother's saying mean?", type:"open", hint:"It's about trusting yourself when others say you're wrong.", model:"The most important thing isn't winning the argument — it's whether you still believe what you saw, even when others tell you you're wrong." },
    { q: "What lesson does Camila learn at the end of this chapter?", type:"open", hint:"Think about what's going to happen again and again.", model:"That a lot of people will tell her she's wrong, and she has to get used to it. She has to keep trusting her own work anyway." }
  ],
  3: [
    { q: "What is a wormhole, and why is the team only using a 'tiny' one?", type:"mc", choices:["A real worm; it's small because of bait size","A shortcut through space; the tiny one can only pass signals, not spaceships","A telescope upgrade","A type of antenna"], correct:1, explain:"A wormhole is a shortcut through space. The tiny one can only pass signals, not objects." },
    { q: "The Fortitude's reply is short and cold. What does it say?", type:"mc", choices:["'Greetings, friends.'","'Their star is dying, they need a new home, arriving in three hundred years.'","'Surrender Earth.'","'We come in peace.'"], correct:1, explain:"That they're the Fortitude, their star is dying, they need a new home, and they'll arrive in three hundred years." },
    { q: "What does Ava notice is special about the Fortitude's message?", type:"mc", choices:["It rhymes","It used a human language","It's digital and mathematical — made of numbers and patterns","It's a song"], correct:2, explain:"They didn't use a human language. The message was digital and mathematical — universal patterns of math and logic." },
    { q: "Why does Annabelle think the Fortitude see humans as 'beneath them'?", type:"open", hint:"Think about what they didn't try to do.", model:"They didn't even try to speak Earth's language. To Annabelle, that was a choice, not an accident." },
    { q: "Why does Camila pay attention when Dr. Webb says the replies could be fake?", type:"open", hint:"Think about how she handles doubt.", model:"Because she always notices when someone doubts her, even when no one else is listening." }
  ],
  4: [
    { q: "Why does Camila want a quick 'win' with the fusion reactor?", type:"mc", choices:["To impress her mother","Dr. Webb wrote another editorial calling the program a waste of money — she wants to prove him wrong","To beat the Olympic deadline","To get more funding from Ardana"], correct:1, explain:"Webb's editorial that morning called the fusion program a waste of public money. Camila wanted a win." },
    { q: "What goes wrong during the fusion test?", type:"mc", choices:["The lights go out","A coolant pipe bursts above Kennedy and hot steam burns her arm and shoulder","The plasma escapes the building","Zoe gets electrocuted"], correct:1, explain:"A small coolant pipe burst above Kennedy. Hot steam burned her arm and shoulder badly." },
    { q: "What does Ava say in the hospital that helps Camila?", type:"mc", choices:["'It wasn't your fault.'","'Bad days teach you something — next time, you'll weigh the choice differently.'","'Sue the manufacturer.'","'Quit while you're ahead.'"], correct:1, explain:"Ava said that bad days teach you something. Failure is part of learning." },
    { q: "When Kennedy finally wakes up, what is the first thing she asks?", type:"mc", choices:["'Where am I?'","'Did we get any good data?'","'Is Camila okay?'","'What time is it?'"], correct:1, explain:"She asks whether they got good data from the reactor before it blew up." },
    { q: "Why do you think Kennedy reacts the way she does, instead of being angry at Camila?", type:"open", hint:"Think about who Kennedy is and what she cares about.", model:"Kennedy cares more about the work than about blame. She chose to be there too. She wants Camila to keep going." }
  ],
  5: [
    { q: "How many seconds are in three hundred years?", type:"mc", choices:["94,608,000","9,460,800,000","946,080","9,460,800"], correct:1, explain:"9,460,800,000 seconds. Big number — but seconds add up fast." },
    { q: "What is fusion energy, in your own words?", type:"open", hint:"Think about the sun.", model:"The same kind of power that makes the sun shine. You squeeze tiny bits of hydrogen together so hard they stick and release a huge burst of energy." },
    { q: "What strange thing does the deep-sea mining ship find?", type:"mc", choices:["A sunken ship","A reading for a metal that doesn't match any known metal — too heavy for iron, too light for lead","A pirate's treasure chest","A dinosaur fossil"], correct:1, explain:"A density reading for an unknown metal — too heavy to be iron, too light to be lead, and it doesn't rust, bend, or break." },
    { q: "Why does Kennedy name the new metal 'Indestructium'?", type:"mc", choices:["After her grandmother","Because nothing she does can leave a mark on it","Because it's expensive","Because Patriya named it"], correct:1, explain:"Nothing leaves a mark on it — not a press, not a torch, not a diamond drill. The metal that cannot be destroyed." },
    { q: "How does Camila act differently when Patriya volunteers, compared to the fusion test?", type:"open", hint:"Compare to the fusion test.", model:"She tells Patriya they will take the time they need. She is not rushing this one. She has learned from Kennedy's accident." }
  ],
  6: [
    { q: "What is the submarine called, and what is it made of?", type:"mc", choices:["The Deep Diver, made of titanium","The Abyss Explorer, covered in early Indestructium plates","The Mariana One, made of glass","The Krakenproof, made of steel"], correct:1, explain:"The Abyss Explorer, covered in the first plates of early Indestructium." },
    { q: "Name a strange creature Patriya sees on the way down — pick one.", type:"mc", choices:["A glowing pink dolphin","A jellyfish the size of a dinner plate","A baby whale","A starfish made of gold"], correct:1, explain:"A pale eyeless fish with needle teeth, a dinner-plate-sized jellyfish, and a bus-sized squid all drift past." },
    { q: "What happens after the drill hits the Indestructium?", type:"mc", choices:["The trench rumbles and a huge shadow rises from below, following the sub for almost three miles","Nothing happens","A school of fish attacks","The drill snaps in half"], correct:0, explain:"The submarine shakes; a piece floats up; then the trench rumbles, silt clouds up, and a huge shadow follows them up nearly three miles before stopping." },
    { q: "What do the sonar images show on the trench wall?", type:"mc", choices:["A buried pirate ship","Long, straight lines and shapes that look almost like doors","A volcanic vent","Whale songs"], correct:1, explain:"Carved-looking lines too straight to be natural. Shapes like doors." },
    { q: "What does Camila mean when she says, 'we may have woken something else'?", type:"open", hint:"What might have been sleeping down there?", model:"That something very old has been living deep in the trench for a long time, and the team's drill may have woken it up." }
  ],
  7: [
    { q: "What is cryosleep, and why is the team thinking about it?", type:"mc", choices:["A new energy drink; it gives them stamina","A way of freezing your body so you can sleep for years without aging much; no human can live 300 years","A meditation app","A type of dream"], correct:1, explain:"Cryosleep slows the heart and freezes the body. They consider it because no human can live 300 years — but cryosleep would let them be there when the Fortitude arrive." },
    { q: "What is the risk Dr. Harper warns them about?", type:"mc", choices:["You might dream forever","About one pod in a hundred has a malfunction — most are minor, but a few have been serious","You'll forget your name","You'll wake up speaking French"], correct:1, explain:"About 1 in 100 pods has a malfunction. Most minor. A few serious. She doesn't pretend." },
    { q: "What does Camila do to say goodbye?", type:"mc", choices:["Bakes cookies with her mother and writes letters to her brother, friend, and old teacher","Throws a giant party","Goes scuba diving","Records a TV special"], correct:0, explain:"She bakes cookies with her mom and writes letters to people she loves." },
    { q: "How long are they asleep the first time, and who wakes them up?", type:"mc", choices:["10 years; the original Dr. Harper","100 years; a robot","41 years; the granddaughter of the original Dr. Harper — a younger Dr. Lila Harper","300 years; Valen"], correct:2, explain:"Forty-one years. Dr. Lila Harper — the granddaughter of the original Dr. Harper — wakes them." },
    { q: "What surprises Camila about Dr. Webb when she wakes up?", type:"open", hint:"Think about what he is still doing.", model:"He is 94 years old and still writing articles against her program. He has never given up." }
  ],
  8: [
    { q: "What is the big breakthrough Zoe and Kennedy make with fusion?", type:"mc", choices:["They make a smaller reactor","They build a fusion reactor with an Indestructium core that holds — producing ten times the energy any earlier reactor managed","They invent a new fuel","They cool the reactor with ice"], correct:1, explain:"An Indestructium core lets the reaction hold. The reactor produces ten times the energy of any previous one." },
    { q: "Why is the Fortitude language so different from human languages?", type:"mc", choices:["It's sung","It has no word for 'maybe,' 'please,' or 'friend' — every sentence is a command, fact, or coordinate","It's only color","It's written backward"], correct:1, explain:"No 'maybe,' no 'please,' no 'friend.' Every sentence is a command, a fact, or a coordinate. They never ask questions." },
    { q: "What pattern does Patriya find in the trench signal?", type:"mc", choices:["Random clicks","Spikes coming in groups of three, then groups of five, repeating over and over","A perfect circle","A musical scale"], correct:1, explain:"Three, then five, then three, then five — over and over. A pattern." },
    { q: "Why does Camila tell the team to keep the trench signal a secret for now?", type:"open", hint:"Think about what people might do if they knew.", model:"They don't yet know what's down there. Telling the public could cause a panic at exactly the wrong time." },
    { q: "The chapter ends comparing the trench signal to what?", type:"mc", choices:["A whale's song","Someone tapping on a wall, waiting to see if anyone taps back","Lightning","A music box"], correct:1, explain:"Someone tapping on a wall, waiting to see if anyone taps back." }
  ],
  9: [
    { q: "Why does Ava quit her job?", type:"mc", choices:["She got a better offer","She is exhausted, hasn't laughed in months, and is afraid that if she takes a day off, the Fortitude will arrive and it will be her fault","She wants to be an astronaut","She got into a fight with Kennedy"], correct:1, explain:"Bone-tired. Six months without laughter. Carrying the weight of every Fortitude word." },
    { q: "When Camila visits Ava, what does she do that surprises Ava?", type:"mc", choices:["Yells at her","Asks what would make Ava's job bearable — and listens","Brings her flowers","Offers her a promotion"], correct:1, explain:"Instead of arguing her out of quitting, Camila asks what would make it bearable. And then she listens." },
    { q: "What gives Ava her breakthrough idea on vacation?", type:"mc", choices:["Watching ocean waves come in groups — small ones and big ones — that the human ear stops noticing","Reading an old book","Talking to a stranger","A dream"], correct:0, explain:"Waves arrive in groups. The Fortitude language might have quiet 'background' signals between the loud bursts." },
    { q: "Who is Valen?", type:"mc", choices:["A Fortitude commander","A Fortitude translator on the alien fleet — the one who has been sending replies to Earth","A new Earth scientist","Camila's cousin"], correct:1, explain:"A Fortitude translator. She has been the one sending replies to Earth all along. Her name is the first word the team decodes." },
    { q: "What does Camila type to Valen first?", type:"mc", choices:["'Surrender.'","'Hello, Valen. My name is Camila.'","'Why are you here?'","'We're ready for you.'"], correct:1, explain:"'Hello, Valen. My name is Camila.'" }
  ],
  10: [
    { q: "What does Camila notice about every Fortitude message?", type:"mc", choices:["They include emojis","Every message is a command, every reply is an acknowledgment — no Fortitude argues or asks for help","They rhyme","They include a date"], correct:1, explain:"Commands and acknowledgments. No arguing. No asking for help." },
    { q: "Why is arguing actually a strength for humans, according to Camila?", type:"open", hint:"Think about how new ideas appear.", model:"Because arguing is how humans fix ideas. Out of arguing, new ideas appear." },
    { q: "What are the three parts of Annabelle's Chaos Plan?", type:"mc", choices:["Food, water, shelter","Jam their messages with disruptors; flood them with choices using small fast teams; make them doubt each other with fake Fortitude orders","Build, attack, retreat","Diplomacy, sanctions, war"], correct:1, explain:"Disruptors jam their orders. Small fast teams overwhelm their decisions. Fake orders in their language make them doubt each other." },
    { q: "What does the word 'asymmetric' mean in Annabelle's plan?", type:"open", hint:"Think about being messy vs. strong.", model:"Humans don't need to be stronger than the Fortitude. They just need to be messier than the Fortitude can handle." },
    { q: "Why does Camila say 'almost' at the end of the chapter?", type:"open", hint:"One country didn't sign.", model:"Because one country refused to sign. The plan still has a hole in it." }
  ],
  11: [
    { q: "Why does President Osei refuse to sign the Accord?", type:"mc", choices:["She wants more lithium money","Because for centuries the world has come to take from Ardana — rubber, diamonds, oil, lithium — and always promised partnership and then left","She doesn't believe the Fortitude exist","Her advisors told her not to"], correct:1, explain:"Three centuries of takers calling themselves partners. Osei doesn't believe this time will be different." },
    { q: "What does Camila tell President Osei that no other diplomat had told her?", type:"mc", choices:["A long list of promises","The truth about her own mistakes — the fusion accident, her doubt, her stubbornness","A funny joke","A cash offer"], correct:1, explain:"Camila admits she's not better than every other person who has made promises to Ardana. She tells the truth about her own mistakes." },
    { q: "What happens to a fusion reactor weeks after Ardana signs the Accord?", type:"mc", choices:["It powers a whole city","Someone secretly plants a timed device that blows it up — eight months of work and ten years of parts destroyed","It runs out of fuel","It's struck by lightning"], correct:1, explain:"A timed device, planted on purpose. Massive damage." },
    { q: "Did Dr. Webb plant the device that destroyed the reactor?", type:"mc", choices:["Yes, he did","No — but he says someone who read his articles their whole life decided to 'do something,' and he had spent sixty years 'leaving gasoline around'","Yes, with help","Nobody knows"], correct:1, explain:"He didn't plant it. But he admits he spent sixty years leaving gasoline around." },
    { q: "Why do you think Camila thanks Dr. Webb at the end of their meeting?", type:"open", hint:"Think about what he finally did.", model:"He finally told the truth. He's going to stop fighting her. Staying angry forever would cost her more than it would cost him." }
  ],
  12: [
    { q: "What is the question Camila asks her team to decide before contacting the Fortitude?", type:"mc", choices:["'Do we surrender?'","'Do we shoot? Or do we talk?'","'Do we run?'","'Do we hide?'"], correct:1, explain:"'Do we shoot? Or do we talk?' That's the choice." },
    { q: "What three possible futures does the team plan for?", type:"mc", choices:["Win, lose, draw","Yes (peace); No (battle); Yes and lie (a sneak attack)","Mars, Venus, Jupiter","Hot, cold, rainy"], correct:1, explain:"Yes — peace. No — battle. Yes and lie — sneak attack." },
    { q: "Why does Annabelle warn Camila about Valen?", type:"mc", choices:["Valen is dangerous","Valen is just one Fortitude — you can't plan a planet's defense around one friend","Valen is a spy","Valen lied to her"], correct:1, explain:"Camila feels like she knows Valen, but Valen is one Fortitude. The defense can't depend on a single friend." },
    { q: "What does Camila's message to the Fortitude offer them?", type:"mc", choices:["A bribe","A choice — fight Earth, or Earth will help them find a new planet and settle it together","Money","A truce only"], correct:1, explain:"Earth offers help finding and settling a new planet. Earth will not give up Earth, but Earth will help." },
    { q: "The Fortitude reply, 'We will discuss.' Why does that small sentence matter?", type:"open", hint:"What have they never had to do before?", model:"In their entire history, the Fortitude have never had to choose. They give orders; they don't discuss. 'We will discuss' means something has changed." }
  ],
  13: [
    { q: "What question does Valen ask Camila that no Fortitude has ever asked before?", type:"mc", choices:["'When are you coming?'","'Why do you help us?'","'Do you have weapons?'","'Are you alone?'"], correct:1, explain:"'Why do you help us?' — a question that has no equivalent in Fortitude language." },
    { q: "What does Valen say happens to a Fortitude who needs help?", type:"mc", choices:["They are honored","They are seen as weaker — the other Fortitude leave them behind","They are healed","They are frozen"], correct:1, explain:"They are weaker. The others leave them. Help is a word Camila taught her." },
    { q: "What secret does Valen tell Camila that she is not supposed to share?", type:"mc", choices:["Her real name","The Fortitude commanders have heard the trench signal too — they think Earth is hiding a second civilization underneath itself, and that humans are lying","The location of their fleet","Their weakness in battle"], correct:1, explain:"They've heard the heartbeat. They think Earth is lying." },
    { q: "How does Valen know Camila is telling the truth?", type:"mc", choices:["She can read minds","She has been reading Camila's words for a hundred years and knows when Camila lies — and Camila almost never does","She uses a lie detector","She trusts everyone"], correct:1, explain:"A hundred years of reading. She knows the cadence of Camila's honesty." },
    { q: "What human word does Valen say she has been 'practicing' for a long time?", type:"mc", choices:["'Goodbye'","'Together' (or 'thank you' — both are correct)","'Sorry'","'Surrender'"], correct:1, explain:"'Together' — and 'thank you.' Both are words humans taught her." }
  ],
  14: [
    { q: "What is wrong when Camila wakes up from the last cryosleep?", type:"mc", choices:["A power outage","An alarm is going off — Patriya's cryopod has malfunctioned","She forgets her name","The Fortitude have already arrived"], correct:1, explain:"Alarms blaring. Patriya's pod failed at the forty-year mark." },
    { q: "Why can't Patriya go to Mars with the rest of the team?", type:"mc", choices:["She refuses to go","Her body is too weak from the pod malfunction — she can't survive a rocket launch","She's needed on Earth","She's afraid"], correct:1, explain:"Her body is too weak. She'll recover, but not in time." },
    { q: "What does Patriya tell Camila not to do?", type:"mc", choices:["Don't cry","Don't feel guilty, and don't delay the most important day in human history because of her","Don't go to Mars","Don't tell the others"], correct:1, explain:"No guilt. No delays. Go." },
    { q: "What does Patriya give each of her teammates before they leave?", type:"mc", choices:["A book","A small gold pin shaped like the Abyss Explorer — she made each one herself, years ago","A photo","A kiss on the forehead"], correct:1, explain:"Tiny gold submarines. She made them herself in a workshop none of them knew about." },
    { q: "How will Patriya be with the team during the Mars handshake?", type:"open", hint:"Think about how she'll watch.", model:"She will watch from her hospital bed on Earth on a video screen. The team will wear her pins on their suits — taking her with them." }
  ],
  15: [
    { q: "What does the Fortitude finally say through the wormhole?", type:"mc", choices:["'We surrender.'","'We will not take Earth. We accept your help in finding a new home.'","'We are coming for war.'","'We need more time.'"], correct:1, explain:"They will not take Earth. They accept the offer." },
    { q: "Why is Mars chosen as the Fortitude's new home?", type:"mc", choices:["It's pretty","It's right next door, has ice and raw materials, and with combined tech can be made livable in about a hundred years","Because the Fortitude love red","Because Earth's leaders own Mars"], correct:1, explain:"Mars is close, has ice and raw materials, and combined tech could terraform it in 100 years instead of 3,000." },
    { q: "What is gravity folding?", type:"open", hint:"Like folding a map.", model:"The Fortitude's way of bending space to travel fast — like folding a map so two cities touch, then stepping across the fold." },
    { q: "Who steps off the first Fortitude pod, and why is that a surprise to Camila?", type:"mc", choices:["A Fortitude commander; she expected a soldier","Valen — Camila has been writing to her for almost a hundred years but has never seen her in person","A robot; she expected a person","A child"], correct:1, explain:"Valen. A century of letters, finally a face." },
    { q: "What brave thing does Camila do when she greets Valen?", type:"mc", choices:["She bows","She takes off her glove and offers her bare hand — bare skin on Mars is risky, even inside the landing zone shield","She hugs her","She salutes"], correct:1, explain:"Bare hand on Mars. Risky. Trusting." }
  ],
  16: [
    { q: "What happens to the trench heartbeat just as the team is celebrating on Mars?", type:"mc", choices:["It speeds up","It stops — the line goes flat for the first time in years","It plays a song","It moves to a new location"], correct:1, explain:"Flatline. For the first time in years." },
    { q: "What does the new message that comes through the wormhole say?", type:"mc", choices:["'We are coming.'","'YOU ARE NOT THE FIRST. WE SPOKE BEFORE YOU WERE BORN. WE HAVE WAITED. WE ARE STILL HERE.'","'Welcome to Mars.'","'Goodbye.'"], correct:1, explain:"'You are not the first to speak through the tunnel. We spoke before you were born. Before your oceans. We have waited. We are still here.'" },
    { q: "Why is Valen afraid of the message?", type:"mc", choices:["She's never been afraid before","Her people heard those exact same words long ago, on their old home, before they ever built ships — and never knew where the voice came from","She thinks it's Camila playing a trick","She doesn't understand it"], correct:1, explain:"The same ancient words. Both Earth and the Fortitude have heard the voice." },
    { q: "How many people are on Camila's team at the end of the book — and who is new?", type:"mc", choices:["Six; nobody new","Seven — the original six women, plus Valen, who joins them at the very end","Five; Patriya is gone","Eight; two Fortitude join"], correct:1, explain:"Seven. The original six, plus Valen." },
    { q: "The book ends with the words 'We are still here.' Whose voice do you think it is?", type:"open", hint:"There's no single right answer — it sets up Book Two.", model:"It might be an ancient civilization that lived on Earth before humans; the same beings who once spoke to the Fortitude; or something even older that has been hiding in the trench. There is no single right answer — it sets up Book Two." }
  ]
};
