const Quiz = ({ chapterNum, onComplete }) => {
  const names = React.useContext(window.NamesContext);
  const A = (s) => window.applyNames(s, names);
  const questions = window.QUIZ[chapterNum] || [];
  const [answers, setAnswers] = React.useState({});
  const [submitted, setSubmitted] = React.useState(false);
  const allAnswered = questions.every((q, i) => {
    const a = answers[i];
    if (q.type === "mc") return a !== void 0;
    return typeof a === "string" && a.trim().length > 0;
  });
  if (submitted) {
    const correctCount = questions.filter((q, i) => q.type === "mc" && answers[i] === q.correct).length;
    const mcTotal = questions.filter((q) => q.type === "mc").length;
    return /* @__PURE__ */ React.createElement("div", { className: "quiz-results" }, /* @__PURE__ */ React.createElement("div", { className: "quiz-score-banner" }, /* @__PURE__ */ React.createElement("div", { className: "qsb-num" }, correctCount, /* @__PURE__ */ React.createElement("span", null, "/", mcTotal)), /* @__PURE__ */ React.createElement("div", { className: "qsb-label" }, "multiple-choice correct", /* @__PURE__ */ React.createElement("br", null), /* @__PURE__ */ React.createElement("span", null, "open answers don't have a wrong answer if you can explain"))), questions.map((q, i) => {
      const a = answers[i];
      const right = q.type === "mc" && a === q.correct;
      return /* @__PURE__ */ React.createElement("div", { key: i, className: `qr-item ${q.type === "mc" ? right ? "qr-right" : "qr-wrong" : "qr-open"}` }, /* @__PURE__ */ React.createElement("div", { className: "qr-q" }, /* @__PURE__ */ React.createElement("span", { className: "qr-num" }, i + 1), A(q.q)), q.type === "mc" ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "qr-row" }, /* @__PURE__ */ React.createElement("span", { className: "qr-tag" }, "YOUR ANSWER"), /* @__PURE__ */ React.createElement("span", { className: right ? "qr-good" : "qr-bad" }, A(q.choices[a]), " ", right ? "\u2713" : "\u2717")), !right && /* @__PURE__ */ React.createElement("div", { className: "qr-row" }, /* @__PURE__ */ React.createElement("span", { className: "qr-tag" }, "CORRECT"), /* @__PURE__ */ React.createElement("span", { className: "qr-good" }, A(q.choices[q.correct]), " \u2713")), /* @__PURE__ */ React.createElement("div", { className: "qr-explain" }, A(q.explain))) : /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "qr-row qr-open-ans" }, /* @__PURE__ */ React.createElement("span", { className: "qr-tag" }, "YOUR ANSWER"), /* @__PURE__ */ React.createElement("span", null, a)), /* @__PURE__ */ React.createElement("div", { className: "qr-explain" }, /* @__PURE__ */ React.createElement("b", null, "A strong answer might say:"), " ", A(q.model))));
    }), /* @__PURE__ */ React.createElement("button", { className: "quiz-next-btn", onClick: onComplete }, "Continue to next chapter \u2192"));
  }
  return /* @__PURE__ */ React.createElement("div", { className: "quiz-card" }, /* @__PURE__ */ React.createElement("div", { className: "quiz-header" }, /* @__PURE__ */ React.createElement("div", { className: "quiz-eyebrow" }, "CHAPTER ", chapterNum, " \xB7 CHECK YOUR UNDERSTANDING"), /* @__PURE__ */ React.createElement("div", { className: "quiz-title" }, "Five questions before you continue"), /* @__PURE__ */ React.createElement("div", { className: "quiz-sub" }, "Some have one right answer. Some are about what you think \u2014 those don't have a wrong answer, as long as you can explain.")), questions.map((q, i) => /* @__PURE__ */ React.createElement("div", { key: i, className: "qq" }, /* @__PURE__ */ React.createElement("div", { className: "qq-q" }, /* @__PURE__ */ React.createElement("span", { className: "qq-num" }, i + 1), A(q.q), q.type === "open" && /* @__PURE__ */ React.createElement("span", { className: "qq-open-tag" }, "your own answer")), q.type === "mc" ? /* @__PURE__ */ React.createElement("div", { className: "qq-choices" }, q.choices.map((c, j) => /* @__PURE__ */ React.createElement("label", { key: j, className: `qq-choice ${answers[i] === j ? "qq-sel" : ""}` }, /* @__PURE__ */ React.createElement("input", { type: "radio", name: `q-${chapterNum}-${i}`, checked: answers[i] === j, onChange: () => setAnswers({ ...answers, [i]: j }) }), /* @__PURE__ */ React.createElement("span", { className: "qq-radio" }), /* @__PURE__ */ React.createElement("span", null, A(c))))) : /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("textarea", { className: "qq-textarea", rows: 3, placeholder: "Type your answer in your own words\u2026", value: answers[i] || "", onChange: (e) => setAnswers({ ...answers, [i]: e.target.value }) }), /* @__PURE__ */ React.createElement("div", { className: "qq-hint" }, "\u{1F4A1} Hint: ", A(q.hint))))), /* @__PURE__ */ React.createElement("button", { className: "quiz-submit-btn", disabled: !allAnswered, onClick: () => setSubmitted(true) }, allAnswered ? "See results" : "Answer all questions to continue"));
};
window.Quiz = Quiz;
